# Netlify Production Configuration
# Car Wash Booking System - Secure Deployment

[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"

# Automatic environment URL configuration
[context.production.environment]
  NEXTAUTH_URL = "${URL}"
  NEXT_PUBLIC_SITE_URL = "${URL}"

[context.deploy-preview.environment]
  NEXTAUTH_URL = "${DEPLOY_PREVIEW_URL}"
  NEXT_PUBLIC_SITE_URL = "${DEPLOY_PREVIEW_URL}"

[context.branch-deploy.environment]
  NEXTAUTH_URL = "${DEPLOY_URL}"
  NEXT_PUBLIC_SITE_URL = "${DEPLOY_URL}"

# ==========================================
# SECURITY HEADERS
# ==========================================

[[headers]]
  for = "/*"
  [headers.values]
    # Security Headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"

    # HSTS - Enforce HTTPS (2 years, include subdomains, preload)
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

    # CSP - Content Security Policy (comprehensive)
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com https://www.google.com https://www.gstatic.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: blob: https://images.unsplash.com https://images.pexels.com https://*.stripe.com;
      font-src 'self' data: https://fonts.gstatic.com;
      connect-src 'self' https://api.stripe.com https://api.sendgrid.com https://*.sentry.io;
      frame-src 'self' https://js.stripe.com https://hooks.stripe.com https://www.google.com;
      frame-ancestors 'none';
      base-uri 'self';
      form-action 'self';
      upgrade-insecure-requests;
      block-all-mixed-content;
    '''

# API Headers - No caching for dynamic content
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, private"
    Pragma = "no-cache"
    Expires = "0"
    X-Robots-Tag = "noindex, nofollow"

# Static Assets - Long cache
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, s-maxage=86400"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Fonts caching
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# ==========================================
# REDIRECTS & REWRITES
# ==========================================

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Remove trailing slashes
[[redirects]]
  from = "/*/"
  to = "/:splat"
  status = 301

# Redirect www to non-www (or vice versa based on preference)
[[redirects]]
  from = "https://www.kiiltoloisto.fi/*"
  to = "https://kiiltoloisto.fi/:splat"
  status = 301
  force = true

# Security redirects - Block common attack vectors
[[redirects]]
  from = "/.env"
  to = "/404"
  status = 404

[[redirects]]
  from = "/.git/*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/wp-admin"
  to = "/404"
  status = 404

[[redirects]]
  from = "/wp-login.php"
  to = "/404"
  status = 404

[[redirects]]
  from = "/.htaccess"
  to = "/404"
  status = 404

[[redirects]]
  from = "/xmlrpc.php"
  to = "/404"
  status = 404

# API Routes (if using Netlify Functions)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# ==========================================
# RATE LIMITING & ANTI-SPAM
# ==========================================

# Forms configuration with spam protection
[forms]
  honeypot = "_gotcha"

# Rate limiting for forms
[[edge_functions]]
  path = "/api/bookings/*"
  function = "rate-limiter"

[[edge_functions]]
  path = "/api/auth/*"
  function = "auth-rate-limiter"

# ==========================================
# PERFORMANCE OPTIMIZATION
# ==========================================

# Enable asset optimization
[build.processing]
  skip = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# ==========================================
# ERROR PAGES
# ==========================================

[[redirects]]
  from = "/500"
  to = "/500.html"
  status = 500

[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# ==========================================
# PLUGINS
# ==========================================

# Plugins commented out to enable deployment
# Can be re-enabled after installing the required packages:
# npm install --save-dev @netlify/plugin-sitemap @netlify/plugin-lighthouse netlify-plugin-checklinks

# # Sitemap generation
# [[plugins]]
#   package = "@netlify/plugin-sitemap"
#
#   [plugins.inputs]
#   buildDir = "out"
#   exclude = [
#     "/admin/*",
#     "/api/*",
#     "/.netlify/*",
#     "/404",
#     "/500"
#   ]
#
# # Lighthouse CI for performance monitoring
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"
#
#   [plugins.inputs.thresholds]
#     performance = 0.9
#     accessibility = 0.9
#     best-practices = 0.9
#     seo = 0.9
#
# # Security headers check
# [[plugins]]
#   package = "netlify-plugin-checklinks"
#
#   [plugins.inputs]
#   skipPatterns = [
#     "/api/*",
#     "mailto:*",
#     "tel:*"
#   ]

# ==========================================
# FUNCTIONS CONFIGURATION
# ==========================================

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

  # Function-specific timeout settings
  [functions."send-email"]
    timeout = 10

  [functions."process-payment"]
    timeout = 15

  [functions."backup-database"]
    schedule = "0 2 * * *" # Daily at 2 AM

# ==========================================
# ENVIRONMENT VARIABLES REQUIREMENTS
# ==========================================

# Required environment variables (documentation)
# DATABASE_URL
# NEXTAUTH_SECRET
# NEXTAUTH_URL
# SENDGRID_API_KEY
# SENDER_EMAIL
# STRIPE_SECRET_KEY
# STRIPE_PUBLISHABLE_KEY
# STRIPE_WEBHOOK_SECRET
# TWILIO_ACCOUNT_SID
# TWILIO_AUTH_TOKEN
# TWILIO_FROM
# SENTRY_DSN
# RECAPTCHA_SITE_KEY
# RECAPTCHA_SECRET_KEY
# BACKUP_ENCRYPTION_KEY
# MONITORING_WEBHOOK_URL