# Render Blueprint for Car Wash Booking System
# This file defines the infrastructure as code for deployment

services:
  # Web Service
  - type: web
    name: car-wash-booking
    env: node
    runtime: node
    plan: starter
    region: oregon
    buildCommand: |
      npm ci --include=dev &&
      npx prisma generate &&
      npm run build
    startCommand: |
      npx prisma migrate deploy &&
      npx prisma db seed &&
      npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: car-wash-db
          property: connectionString
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: DATABASE_POOL_SIZE
        value: "10"
      - key: DB_MAX_CONNECTIONS
        value: "20"
      - key: DATABASE_CONNECTION_TIMEOUT
        value: "30000"
      - key: DB_POOL_TIMEOUT
        value: "10000"
      - key: DB_IDLE_TIMEOUT
        value: "60000"

# PostgreSQL Database
databases:
  - name: car-wash-db
    plan: free
    databaseName: carwash_booking
    user: carwash_user
    region: oregon

# Environment Variables to be set manually in Render Dashboard:
#
# REQUIRED (Payment & Email):
# - STRIPE_SECRET_KEY (e.g., sk_live_...)
# - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY (e.g., pk_live_...)
# - STRIPE_WEBHOOK_SECRET (e.g., whsec_...)
# - SENDGRID_API_KEY (e.g., SG....)
# - SENDER_EMAIL (e.g., noreply@yourdomain.com)
#
# OPTIONAL (Analytics & Monitoring):
# - SENTRY_DSN (for error tracking)
# - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY (for maps)
# - NEXT_PUBLIC_GA_ID (for analytics)
#
# Note: NEXTAUTH_URL and NEXT_PUBLIC_SITE_URL will be auto-generated
# based on your service URL (e.g., https://your-app-name.onrender.com)