# Render Blueprint for Car Wash Booking System
# This file defines the infrastructure as code for deployment

services:
  # Web Service
  - type: web
    name: car-wash-booking
    env: node
    runtime: node
    plan: starter
    region: oregon
    buildCommand: |
      npm ci --include=dev &&
      npx prisma generate &&
      DATABASE_URL="postgresql://placeholder:placeholder@placeholder:5432/placeholder" npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: car-wash-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: car-wash-redis
          property: connectionString
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: BUILD_ID
        generateValue: true
      - key: PORT
        value: "3000"
      # Database optimization
      - key: DATABASE_POOL_SIZE
        value: "10"
      - key: DB_MAX_CONNECTIONS
        value: "20"
      - key: DATABASE_CONNECTION_TIMEOUT
        value: "30000"
      - key: DB_POOL_TIMEOUT
        value: "10000"
      - key: DB_IDLE_TIMEOUT
        value: "60000"
      # Redis configuration
      - key: REDIS_KEY_PREFIX
        value: "carwash:prod:"
      - key: REDIS_DEFAULT_TTL
        value: "3600"
      - key: REDIS_ENABLE_COMPRESSION
        value: "true"
      # Security
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      # Business configuration
      - key: BUSINESS_NAME
        value: "Kiilto Loisto Autopesula"
      - key: LOYALTY_PROGRAM_ENABLED
        value: "true"
      - key: REAL_TIME_UPDATES_ENABLED
        value: "true"

# PostgreSQL Database
databases:
  - name: car-wash-db
    plan: starter  # Upgrade from free for production
    databaseName: carwash_booking
    user: carwash_user
    region: oregon

# Redis Cache for session management and real-time features
services:
  - type: redis
    name: car-wash-redis
    plan: starter  # Redis add-on
    region: oregon
    maxmemoryPolicy: allkeys-lru

# Environment Variables to be set manually in Render Dashboard:
#
# REQUIRED (Payment & Email):
# - STRIPE_SECRET_KEY (e.g., sk_live_...)
# - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY (e.g., pk_live_...)
# - STRIPE_WEBHOOK_SECRET (e.g., whsec_...)
# - SENDGRID_API_KEY (e.g., SG....)
# - SENDER_EMAIL (e.g., noreply@yourdomain.com)
#
# OPTIONAL (Analytics & Monitoring):
# - SENTRY_DSN (for error tracking)
# - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY (for maps)
# - NEXT_PUBLIC_GA_ID (for analytics)
#
# Note: NEXTAUTH_URL and NEXT_PUBLIC_SITE_URL will be auto-generated
# based on your service URL (e.g., https://your-app-name.onrender.com)