# Netlify Production Configuration - Fixed
# Car Wash Booking System

[build]
  command = "npm install && npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"

# Include the Next.js plugin - REQUIRED for proper Next.js deployment
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Fixed environment URL configuration
[context.production.environment]
  NEXTAUTH_URL = "https://kiiltoloisto.fi"
  NEXT_PUBLIC_SITE_URL = "https://kiiltoloisto.fi"

[context.deploy-preview.environment]
  NEXTAUTH_URL = "${DEPLOY_PREVIEW_URL}"
  NEXT_PUBLIC_SITE_URL = "${DEPLOY_PREVIEW_URL}"

[context.branch-deploy.environment]
  NEXTAUTH_URL = "${DEPLOY_URL}"
  NEXT_PUBLIC_SITE_URL = "${DEPLOY_URL}"

# ==========================================
# SECURITY HEADERS (Simplified)
# ==========================================

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains"

# API Headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Static Assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ==========================================
# API REDIRECTS (Essential)
# ==========================================

# API Routes to Netlify Functions
[[redirects]]
  from = "/api/services"
  to = "/.netlify/functions/services-index"
  status = 200

[[redirects]]
  from = "/api/services/:id"
  to = "/.netlify/functions/services-id"
  status = 200

[[redirects]]
  from = "/api/bookings/availability"
  to = "/.netlify/functions/bookings-availability"
  status = 200

[[redirects]]
  from = "/api/bookings/create"
  to = "/.netlify/functions/bookings-create"
  status = 200

[[redirects]]
  from = "/api/bookings/:id"
  to = "/.netlify/functions/bookings-id"
  status = 200

[[redirects]]
  from = "/api/payment/create-session"
  to = "/.netlify/functions/payment-create-session"
  status = 200

[[redirects]]
  from = "/api/payment/webhook"
  to = "/.netlify/functions/payment-webhook"
  status = 200

# ==========================================
# FUNCTIONS CONFIGURATION
# ==========================================

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"